const EARTH_RADIUS_M = 6371e3;

const NORMAL_ROLE_NAME = "Normal";

const ADMIN_ROLE_NAME = "Administrador";

const NODE = "NODE"

const SUBNODE = "SUBNODE"

const LOSTPOINT = "LOSTPOINT"

const VIA_NODO_TYPE = "VIA"
const ROUTE_NODO_TYPE = "ROUTE"
const INTEREST_NODO_TYPE = "INTEREST"
const ENTRANCE_NODO_TYPE = "ENTRANCE"
const ACCESS_NODO_TYPE = "ACCES"

const CLASSROOM_CATEGORY = "CLASSROOM"
const BATHROOM_CATEGORY = "BATHROOM"

module.exports = { EARTH_RADIUS_M, NORMAL_ROLE_NAME, ADMIN_ROLE_NAME, NODE, SUBNODE, LOSTPOINT, BATHROOM_CATEGORY, CLASSROOM_CATEGORY, ACCESS_NODO_TYPE, ENTRANCE_NODO_TYPE, INTEREST_NODO_TYPE, ROUTE_NODO_TYPE, VIA_NODO_TYPE };
