const EARTH_RADIUS_M = 6371e3;

const NORMAL_ROLE_NAME = "Normal";

const ADMIN_ROLE_NAME = "Administrador";

const NODE = "NODE"

const SUBNODE = "SUBNODE"

const LOSTPOINT = "LOSTPOINT"

module.exports = { EARTH_RADIUS_M, NORMAL_ROLE_NAME, ADMIN_ROLE_NAME, NODE, SUBNODE, LOSTPOINT };
